apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-nas-1
  namespace: default
spec:
  volumeSnapshotClassName: default-snapclass
  source:
    persistentVolumeClaimName: pvc-disk